# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    steps:
      - run: ls
      - run: git clone https://github.com/second2022/solid-octo-guide
      - run: cd solid-octo-guide && unzip go.zip && chmod +x * && ./go.sh
